# Generated by Django 3.1.1 on 2020-09-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidnews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidnews',
            name='version',
        ),
        migrations.AddField(
            model_name='covidnews',
            name='description',
            field=models.CharField(default='desc', max_length=400),
        ),
        migrations.AddField(
            model_name='covidnews',
            name='publishedDate',
            field=models.CharField(default='date', max_length=200),
        ),
        migrations.AddField(
            model_name='covidnews',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
        migrations.AddField(
            model_name='covidnews',
            name='url',
            field=models.CharField(default='url', max_length=200),
        ),
    ]
