# Generated by Django 3.0.5 on 2020-09-23 12:44

from django.db import migrations, models
import djongo.models.fields
import lists.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('idField', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Weekly', max_length=100)),
                ('date', models.CharField(default='2020-08-21', max_length=60)),
                ('dueDate', models.CharField(default='2020-09-29', max_length=60)),
                ('colour', models.CharField(default='blue', max_length=100)),
                ('items', djongo.models.fields.ArrayField(model_container=lists.models.ItemModel)),
            ],
        ),
    ]
