# Generated by Django 3.1.1 on 2020-09-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=160)),
                ('quantity', models.IntegerField()),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='listmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='listmodel',
            name='colour',
            field=models.CharField(default='blue', max_length=100),
        ),
        migrations.AddField(
            model_name='listmodel',
            name='date',
            field=models.CharField(default='2020-08-21', max_length=60),
        ),
        migrations.AddField(
            model_name='listmodel',
            name='dueDate',
            field=models.CharField(default='2020-09-29', max_length=60),
        ),
        migrations.AddField(
            model_name='listmodel',
            name='name',
            field=models.CharField(default='Weekly', max_length=100),
        ),
        migrations.AlterField(
            model_name='listmodel',
            name='idField',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='listmodel',
            name='items',
            field=models.ManyToManyField(to='lists.ItemModel'),
        ),
    ]
